CUDA_VISIBLE_DEVICES=0 python src/train_bash.py \
    --stage sft \
    --model_name_or_path /data/ccq/models/Baichuan2-13B-Chat \
    --do_train \
    --dataset Baichuan2_characters \
    --finetuning_type lora \
    --output_dir output/Baichuan2_characters \
    --overwrite_cache \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 2.0 \
    --plot_loss \
    --fp16 \
    --quantization_bit 4
